from dataclasses import dataclass

from app.models import DocumentChunk, Product


@dataclass(frozen=True)
class BundleRecipe:
    """套餐由业务配置决定；模型不参与任意拼装 SKU。"""

    bundle_id: str
    name: str
    sku_ids: tuple[str, ...]
    bundle_price_fen: int
    signals: tuple[str, ...]
    routine: tuple[str, ...]
    caution: str

# 前三个商品组成可推荐套餐；后两个是刻意保留的反例数据，用于验证下架和缺货过滤。
PRODUCTS: list[Product] = [
    Product(
        sku_id="sku_cleanser_100",
        name="澄肌氨基酸洁面乳",
        spec="100ml",
        price_fen=12_900,
        stock=42,
        on_sale=True,
        approved=True,
        tags=["温和清洁", "干燥感", "敏感倾向"],
        ingredients=["氨基酸表活", "甘油"],
        usage="早晚取适量加水起泡，轻柔清洁后冲洗。",
        cautions="避免进入眼睛；皮肤破损处请勿使用。",
    ),
    Product(
        sku_id="sku_serum_30",
        name="澄肌屏障修护精华",
        spec="30ml",
        price_fen=26_900,
        stock=18,
        on_sale=True,
        approved=True,
        tags=["屏障修护", "紧绷感", "干燥感"],
        ingredients=["神经酰胺", "泛醇", "角鲨烷"],
        usage="洁面后取 2–3 滴，轻拍至吸收。",
        cautions="首次使用建议局部测试；出现不适请停止使用。",
    ),
    Product(
        sku_id="sku_cream_50",
        name="澄肌神经酰胺面霜",
        spec="50g",
        price_fen=20_900,
        stock=26,
        on_sale=True,
        approved=True,
        tags=["保湿", "屏障修护", "干燥感"],
        ingredients=["神经酰胺", "胆固醇", "透明质酸钠"],
        usage="精华后取豌豆大小，均匀涂抹面部。",
        cautions="首次使用建议局部测试；避开破损皮肤。",
    ),
    Product(
        sku_id="sku_oil_cleanser_120",
        name="澄肌净澈控油洁面",
        spec="120ml",
        price_fen=11_900,
        stock=36,
        on_sale=True,
        approved=True,
        tags=["温和清洁", "控油", "油光", "毛孔"],
        ingredients=["葡糖苷表活", "锌 PCA"],
        usage="早晚取适量起泡后清洁，避开眼周。",
        cautions="不要与强清洁产品叠加频繁使用。",
    ),
    Product(
        sku_id="sku_oil_serum_30",
        name="澄肌清透平衡精华",
        spec="30ml",
        price_fen=24_900,
        stock=31,
        on_sale=True,
        approved=True,
        tags=["控油", "油光", "毛孔", "轻盈保湿"],
        ingredients=["烟酰胺", "锌 PCA", "甜菜碱"],
        usage="洁面后取 2–3 滴，轻拍全脸。",
        cautions="初次使用建议隔天建立耐受。",
    ),
    Product(
        sku_id="sku_oil_lotion_50",
        name="澄肌轻盈水润乳",
        spec="50ml",
        price_fen=17_900,
        stock=47,
        on_sale=True,
        approved=True,
        tags=["轻盈保湿", "控油", "油光"],
        ingredients=["透明质酸钠", "泛醇"],
        usage="精华后薄涂，T 区可酌情减量。",
        cautions="避开破损皮肤。",
    ),
    Product(
        sku_id="sku_bright_serum_30",
        name="澄肌焕亮匀净精华",
        spec="30ml",
        price_fen=29_900,
        stock=22,
        on_sale=True,
        approved=True,
        tags=["焕亮", "暗沉", "均匀肤色"],
        ingredients=["烟酰胺", "N-乙酰葡糖胺", "泛醇"],
        usage="晚间洁面后取 2–3 滴，避开眼周。",
        cautions="白天使用需配合防晒；敏感时先做局部测试。",
    ),
    Product(
        sku_id="sku_bright_cream_50",
        name="澄肌焕亮修护面霜",
        spec="50g",
        price_fen=21_900,
        stock=28,
        on_sale=True,
        approved=True,
        tags=["焕亮", "暗沉", "保湿"],
        ingredients=["神经酰胺", "抗坏血酸葡糖苷"],
        usage="精华后取豌豆大小均匀涂抹。",
        cautions="白天使用需配合防晒。",
    ),
    Product(
        sku_id="sku_offline_30",
        name="澄肌焕亮精华",
        spec="30ml",
        price_fen=29_900,
        stock=99,
        on_sale=False,
        approved=True,
        tags=["焕亮"],
        ingredients=["烟酰胺"],
        usage="晚间使用。",
        cautions="请按说明使用。",
    ),
    Product(
        sku_id="sku_out_of_stock_30",
        name="澄肌舒缓精华",
        spec="30ml",
        price_fen=23_900,
        stock=0,
        on_sale=True,
        approved=True,
        tags=["舒缓", "干燥感"],
        ingredients=["积雪草提取物"],
        usage="洁面后使用。",
        cautions="请按说明使用。",
    ),
]

BUNDLE_RECIPES: tuple[BundleRecipe, ...] = (
    BundleRecipe(
        bundle_id="bundle_barrier_7d",
        name="7 日屏障修护套餐",
        sku_ids=("sku_cleanser_100", "sku_serum_30", "sku_cream_50"),
        bundle_price_fen=52_800,
        signals=("干", "紧绷", "保湿", "修护", "换季", "泛红", "敏感"),
        routine=("1 温和洁面", "2 修护精华", "3 保湿面霜"),
        caution="首次使用先做局部测试；破溃、持续不适或严重红肿请停止使用并线下就医。",
    ),
    BundleRecipe(
        bundle_id="bundle_balance_7d",
        name="7 日清透平衡套餐",
        sku_ids=("sku_oil_cleanser_120", "sku_oil_serum_30", "sku_oil_lotion_50"),
        bundle_price_fen=48_800,
        signals=("油", "油光", "出油", "毛孔", "控油", "闷"),
        routine=("1 净澈洁面", "2 清透精华", "3 轻盈保湿"),
        caution="避免频繁叠加强清洁产品；如有持续刺痛或红肿，请停止使用并咨询专业人士。",
    ),
    BundleRecipe(
        bundle_id="bundle_bright_7d",
        name="7 日焕亮保湿套餐",
        sku_ids=("sku_cleanser_100", "sku_bright_serum_30", "sku_bright_cream_50"),
        bundle_price_fen=56_800,
        signals=("暗沉", "焕亮", "提亮", "美白", "肤色不均"),
        routine=("1 温和洁面", "2 焕亮精华", "3 焕亮面霜"),
        caution="白天请配合防晒；初次使用建议局部测试，敏感或不适时停止使用。",
    ),
)

DOCUMENTS: list[DocumentChunk] = [
    # 资料也保留版本号，前端和审计可以说明回答依据来自哪个审核版本。
    DocumentChunk(
        id="chunk_cleanser_v18",
        sku_id="sku_cleanser_100",
        title="温和洁面使用说明",
        version="v1.8",
        content="氨基酸表活体系，适合希望减少洗后紧绷感的温和清洁场景。",
        tags=["温和清洁", "紧绷感", "干燥感"],
        approved=True,
        on_sale=True,
    ),
    # 下架商品的资料必须留在数据集中，才能回归验证它不会进入模型上下文。
    DocumentChunk(
        id="chunk_serum_v21",
        sku_id="sku_serum_30",
        title="屏障修护精华成分资料",
        version="v2.1",
        content="含神经酰胺、泛醇与角鲨烷，资料审核通过；建议洁面后使用。",
        tags=["屏障修护", "紧绷感", "干燥感"],
        approved=True,
        on_sale=True,
    ),
    DocumentChunk(
        id="chunk_cream_v13",
        sku_id="sku_cream_50",
        title="神经酰胺面霜产品资料",
        version="v1.3",
        content="神经酰胺、胆固醇与透明质酸钠组成的保湿护理资料，建议在精华后使用。",
        tags=["保湿", "屏障修护", "干燥感"],
        approved=True,
        on_sale=True,
    ),
    DocumentChunk(
        id="chunk_oil_cleanser_v11",
        sku_id="sku_oil_cleanser_120",
        title="净澈控油洁面使用说明",
        version="v1.1",
        content="葡糖苷表活搭配锌 PCA，适合希望减轻油光且保持温和清洁感的场景。",
        tags=["控油", "油光", "毛孔"],
        approved=True,
        on_sale=True,
    ),
    DocumentChunk(
        id="chunk_oil_serum_v12",
        sku_id="sku_oil_serum_30",
        title="清透平衡精华资料",
        version="v1.2",
        content="含烟酰胺、锌 PCA 与甜菜碱，资料建议洁面后轻拍使用。",
        tags=["控油", "毛孔", "轻盈保湿"],
        approved=True,
        on_sale=True,
    ),
    DocumentChunk(
        id="chunk_oil_lotion_v10",
        sku_id="sku_oil_lotion_50",
        title="轻盈水润乳产品资料",
        version="v1.0",
        content="轻盈保湿配方，资料建议在精华后薄涂，T 区可酌情减量。",
        tags=["轻盈保湿", "油光"],
        approved=True,
        on_sale=True,
    ),
    DocumentChunk(
        id="chunk_bright_serum_v14",
        sku_id="sku_bright_serum_30",
        title="焕亮匀净精华成分资料",
        version="v1.4",
        content="含烟酰胺与 N-乙酰葡糖胺，资料建议晚间洁面后使用，白天注意防晒。",
        tags=["焕亮", "暗沉", "均匀肤色"],
        approved=True,
        on_sale=True,
    ),
    DocumentChunk(
        id="chunk_bright_cream_v10",
        sku_id="sku_bright_cream_50",
        title="焕亮修护面霜产品资料",
        version="v1.0",
        content="含神经酰胺与抗坏血酸葡糖苷，建议在焕亮精华后使用并注意白天防晒。",
        tags=["焕亮", "暗沉", "保湿"],
        approved=True,
        on_sale=True,
    ),
    DocumentChunk(
        id="chunk_offline_v10",
        sku_id="sku_offline_30",
        title="焕亮精华资料",
        version="v1.0",
        content="仅用于验证下架资料不能被检索或推荐。",
        tags=["焕亮"],
        approved=True,
        on_sale=False,
    ),
]
